### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by CelineFMY** [Adrakaris/cyclegans#1]
Where can I find the pretrained model?

**Comment by Adrakaris** [comment]
The pretrained models are not available as this is a research project, there are several different models and the raw files are quite large, you will have to train yourself, sorry. The dataset is provided already, so you can just set everything up and get going.

In my experience the DenseNet or DenseNet + MSLE works best. Deformable layers are very slow since I could not find a directML-compatible version and don't have CUDA.
